- import_data_bot.py
The prior implementation would pull the median item, but this strategy won't always return the most even matchup. (example test case: [0.49, 0.50, 0.51, 0.52, 0.53, 0.53, 0.53, 0.53]).
This PR changes it so that it uses a priority-queue to get the matchup which is closest to even (0.50)
> feat: use pq to calculate most even match

- discord_bots/commands.py
- discord_bots/utils.py
- Handle all error cases, so the stats command will always send a `Response` to the `Interaction`
- Simplify the logic for getting the players wins, losses, ties, etc.. to be more generic
- Add support for displaying stats when the user has not played a game in a Categorized Queue
> Refactor stats to be more robust and simplify

- discord_bots/cogs/economy.py
- discord_bots/commands.py
- discord_bots/tasks.py
Fixed a couple of immediate errors with predictions no timing out, or refunding correctly on cancel game.
Need to cater for Delete Game, but will do in separate branch so as to push this through quicker.
Prediction embeds also not updating after a rebalance (after refund).
> Fixed prediction refunding & timeout

- discord_bots/commands.py
- discord_bots/main.py
In setgamecode, the interaction response was timing out because it wasn't being replied to in time. This was due to sending each player the game code taking too much time, so the solution was to `interaction.response.defer()` and then `interaction.followup.send(...)` later.
> fix: setgamecode interaction response timing out, log all errors

- discord_bots/commands.py
Small fix to adjust both references of "Average Rating" -> "Average μ", to match the recently merged changes.
1. In the created game embed
2. In status, when there's an active InProgressGame
> fix: rename average rating to average μ

- discord_bots/models.py
This might cause breakages since sqlite was letting foreign key constraint violations slide, but I feel as if this would be a good thing to enable moving forwards. Especially if the goal is to be compatible with psql.
> fix: enable foreing key constriants for sqlite

- discord_bots/checks.py
- discord_bots/cogs/queue.py
- discord_bots/cogs/raffle.py
- discord_bots/commands.py
- discord_bots/main.py
- discord_bots/queues.py
- discord_bots/tasks.py
- discord_bots/utils.py
- fixed an invalid import that was accidentally added from the previous PR
- deleting queue_waitlist messages ("Your game has just finished, you will be added to ... in ... seconds") messages were rate limiting the bot, since a discord API call was being made for each message. Switched to `bot.channel.delete_messages()` which bulk deletes them by making a single API call
- the add player status message has been reworked, it now combines all the AddPlayerMessages into a singular message. This applies to adds from anywhere, like from the QueueWaitlist:
Note: The first embed is generted in !mockqueue and I only added myself to !mockqueue for testing, wasn't pushed
- misc style fixes
> fix: queue waitlist message delete rate limiting, invalid import, queuewaitlist status message now combines for all players

- discord_bots/cogs/in_progress_game.py
- discord_bots/cogs/queue.py
- discord_bots/commands.py
- discord_bots/config.py
- discord_bots/main.py
- discord_bots/models.py
- discord_bots/tasks.py
- discord_bots/utils.py
Various reworks and bug fixes:
1. Logging is now done to both stdout/stderr and a rotating file handler, which outputs to `bot.log` (max size 32Mib, 3 backups so max possible log size is 120MiB)
2. Fixed two reproducible db locks: one when finishing a game, the other when autosubbing/subbing
3. In `status, add, del, create_in_progress_game_embed, queue_waitlist, etc...`, use Player.name instead of using the discord.py APIs since this column is now updated with the player's Discord Display Name
4. both sub and autosub will now fill the team "columns" with a "diff" of the before/after. Here's an example:
Any player who was newly added to a team after the sub/autosub will be highlighted green while a player who did not change will be grey
5. Use asyncio.gather to run blocking IO coroutines …
> Fix db locks in concurrent on_messages, rework autosub/sub style, use asyncio.gather, run get_even_teams in separate process

- discord_bots/commands.py
- discord_bots/utils.py
`_move_game_players` was assuming that the first row in the `in_progress_game_channel` table corresponded to the voice_channel1 and the second corresponded to voice_channel2. Instead, it now searches for the correct voice channels based on the team names, which is currently how they are created.
> fix: incorrect var name, _movegameplayers finds correct voice channels instead of assuming based on row order

- .gitignore
I noticed after running the server locally, that the `bot.log` file it produces is not excluded by Git.
This PR adds the affected file to the git ignore list.
> Add `bot.log` to `.gitignore`

- .dockerignore
- Dockerfile-base
It was requested that vim should be in the `technitaur/tribesbot:base` image for the Docker installation. I have updated the `Dockerfile-base` file to reflect this. My image on Dockerhub has also been updated: [link](https://hub.docker.com/layers/technitaur/tribesbot/base/images/sha256:5ff416655f23f04f3ee48b1443baa407ca5b8a9fd18389cf34473fb608c0d9f9?uuid=026B5842-0DAD-4FAB-9B06-C5085B9E68D1)
Those who have already been using the base image may need to delete it from their system in order to receive the updated version, but I don't know for sure. Try restarting your container and see if you can run vim in it. If that doesn't work, delete the container and the image (but not your volume!) and then `docker compose build && docker compose up` again.
This is a new process for me, so I …
> Add vim to Dockerfile-base, Dockerhub image also updated

- .env.example
- discord_bots/commands.py
- discord_bots/config.py
- Adds a new `.env` variable: `ADMIN_AUTOSUB`.
- Default = Faluse
- When True, `!autosub` is only able to be used by admins, via the `.checks.is_admin()` check
> Admin only autosub

- .dockerignore
Per discord we were seeing issues starting the bots in docker as a result of incompatible local virtualenvs being copied in during the main build.
This just excludes the local venv from being included in the docker copy.
Testing: before adding the line to the dockerignore, I got the error with `alembic` for `cannot execute` (caused by a shebang pointing at a path on my local system) and afterwards, it boots successfully.
> Prevent local .venv being copied into docker image and overwriting deps

- discord_bots/utils.py
- Fixed an issue where the `print_leaderboard` would always post a new message, instead of editing the previous one
- Condensed the format as much as possible to help readability on mobile, however this isn't the long-term solution
> fix: leaderboard not editing last leaderboard message, condensed format

- docs/running/RUNNING_DIRECTLY.md
- requirements.txt
Tiny, tiny PR just because I couldn't get requirements installed on my machine due to:
* a [known issue with Pyyaml](https://github.com/yaml/pyyaml/issues/736) below 6.0.1
* the version of `Pillow` in the deps not being compatible with MacOS on ARM
For PyYaml it's a patch version bump so should be safe. And Pillow is only even here as a transitive dependency of scipy which is used in the script for plotting Trueskill, it shouldn't be actually required to run the app.
> Bump pyyaml 6.0 -> 6.0.1 and Pillow 9.0.1 -> 10.3.0 to avoid local install issues

- discord_bots/utils.py
Leaderboard footer text still displayed `!disableleaderboard` which has been converted to `/player toggleleaderboard`
Updates embed footer to be representative of new command
> Update Leaderboard Footer

- discord_bots/cogs/base.py
- discord_bots/cogs/category.py
- discord_bots/cogs/in_progress_game.py
- discord_bots/views/base.py
- discord_bots/views/configure_category.py
- discord_bots/views/confirmation.py
**Dependant on PR #93**
Introduces `/category configure <category>` that collects together the various functions required for both creating & editing a category.
When running the command, the user is presented with a view of various options for each logical grouping of settings that can be configured;
Clicking each button launches a Modal for TextInput of values (placeholder values pulled from existing category values).
After making a change via one of the buttons / select menus, a log of pending changes is made into the original embed;
The changes made are left pending and stored locally within the view, until the user clicks *Save*.
This makes use of the existing confirmation buttons, and when confirmed the category is then added/updated in the DB.
The cancel button will stop the view …
> Category configure

- discord_bots/cogs/base.py
- discord_bots/cogs/category.py
- discord_bots/cogs/in_progress_game.py
- discord_bots/cogs/map.py
- discord_bots/views/base.py
- discord_bots/views/configure_category.py
- discord_bots/views/configure_map.py
- discord_bots/views/confirmation.py
**Dependant on PR #98**
In a similar fashion to PR #98, this PR includes the `/map configure <map_name>` command.
Maps being a very simple entity type, the configuration setup is much simpler, and the only configurable variables are `map.short_name` & `map.full_name`.
Configuration ensures that both are filled.
Creating map names through interaction / modal allows for whitespace in names, where the previous context commands did not.
All basic configuration functionality (save / cancel / timeout etc) are duplicated from category, to maintain a standard functionality across entities.
`/map add` has been removed
**DO NOT MERGE UNTIL AFTER PR #98**
> Map configure

- alembic/versions/20240504092141_eac69ad70805_make_last_game_finished_at_non_nullable.py
- discord_bots/models.py
- discord_bots/tasks.py
In order to address the issue that a player who has not played since decay was introduced will never decay, this PR makes the column non-nullable. To facilitate this it sets the server default to the current timestamp on creation, and updates all existing null rows to the current timestamp (i.e. we do not try to retroactively decay players who are not active, but we can start decaying them from the time of upgrade).
One downside to this is that the alembic migration is not strictly reversible – it updates existing rows and therefore a downgrade will not magically make those rows have a null timestamp again.
> Make PCT last_game_finished_at non-null and defaulting to current timestamp

- discord_bots/tasks.py
The current AFK timeout message, which posts a `discord.Embed` doesn't render properly for mobile hence the push notification will look like this:
This PR switches it to a regular message to fix that.
Note: desktop doesn't have this issue, but I felt like the AFK timer message would be more applicable to someone checking their phone. 
Leaving this PR up if anyone has any comments
> fix: afk timeout to normal message for mobile notifications

- discord_bots/cogs/list.py
- discord_bots/cogs/map.py
- discord_bots/tasks.py
1. Changed all `/list...` commands (as well as `/map globalstats`) to reply ephemerally.
2. Fixed an issue with the player names in the queue status not displaying based on insertion order. The issue was that it was selecting from the `Player` table and joining with the `QueuePlayer` table, so it was displaying based on the insertion order of the `Player` table.
3. Sigma decay not updating rank
> style: make list commands ephemeral. fix: queue status player sorting, sigma decay not updating rank

- discord_bots/cogs/common.py
- discord_bots/commands.py
- discord_bots/utils.py
- Condensed the format of `/stats` to make it a little more compact and readable
- Upped the rounding for the win probabilities of the teams back up to 1 digit
- Bolded the player names of the winning team to help improve readability
Examples:
> Condense stats format, bold winning player names, increase win pct rounding to 1 digit from 0

- discord_bots/cogs/common.py
- discord_bots/utils.py
Changed the game code field in the in progress game's embed to be a code block, so you can 1 click copy the code and add a bit of syntax highlighting for flavor:
> style: make game code embed field a code block

- discord_bots/cogs/admin.py
- discord_bots/cogs/common.py
- discord_bots/cogs/map.py
- discord_bots/cogs/raffle.py
- discord_bots/cogs/rotation.py
- discord_bots/cogs/vote.py
- discord_bots/utils.py
A few changes are included; `!sync` is required:
1. `/map changequeuemap` -> `/admin setqueuemap`
2. `/map changegamemap` -> `/admin setgamemap`
3. Fixed an issue where some commands were querying based on the map full name, while the autocomplete returned the shortname
4. Fixed the `/setgamecode` not using a code block for the code in the embed sent to DMs
> fix: map autocomplete issue, setgamecode code block, move some commands to admin

- discord_bots/cogs/common.py
- discord_bots/cogs/map.py
- discord_bots/commands.py
- discord_bots/tasks.py
- discord_bots/utils.py
- discord_bots/views/configure_map.py
Since code blocks inside embeds are still broken, I went ahead and reworked the leaderboard, `/stats`/ and `/map stats`.
The leaderboard has come full circle and is basically the same as the old one, aside from some minor differences:
`/stats` I just threw inside of a regular message in the interim, but I'll be looking into some alternate formatting in the future
`/map stats` (and `/map globalstats`) are the same, where they're just inside a regular message
> fix: leaderboard, stats, and mapstats broken style

- discord_bots/cogs/admin.py
- discord_bots/commands.py
- discord_bots/utils.py
`del` will now remove the the appropriate queue_waitlist_player based on the args they pass in. The behavior is the same as it is for deleting from queues -- i.e., no target, ordinal as target, name as target, or a combination.
It's also worth noting that any negative case of using `del` (not in any queues, no valid queues specified, etc...) will now be ignored and no message is sent. It may be confusing to the user, but it's less spamy. The previous behavior always posted a message saying "no valid queues specified" which I felt like was both confusing and spamy.
> fix: del not removing player from queue_waitlist_player

- discord_bots/commands.py
- discord_bots/utils.py
Don't show the map image on sub/autosub, since the width of the image clamps the width of the embed, which can cause the code block to have undesirable word wrapping. This change improves readability
> Do not show map image on sub and autosub

- discord_bots/cogs/queue.py
- discord_bots/cogs/vote.py
- discord_bots/commands.py
- discord_bots/tasks.py
- discord_bots/utils.py
1. Updated the style of `/queue showrotation`
2. Update the style of `/vote skip`
3. Recompute `average_mu` when sub or autosub is used
4. Attempt to fix queue sniping, by moving message deletes to the end of the `queue_waitlist_task`
5. Show voteskip amount in status embed, next to the next map (if there are any votes)
6. Add map image thumbnails to status, vote skip, and some other places
7. Show the next map when adding to a queue, works for adds that target multiple rotations
> Refactors, bug fixes and style improvements

- discord_bots/cogs/player.py
This adds commands to set player sigma and mu directly. This comes from several requests from the T1 community. We've been doing this manually already in special cases (like when an old VIP veteran shows up we give them a very low mu for a good welcoming experience).
In the future it would probably be good to record these to the database and/or announce them to some private channel to add accountability
> feat: add command to set mu/sigma directly

- alembic/versions/20250607181932_54080d3503e2_make_role_id_bigint.py
the t1 db state was bad due to converting from sqlite, and while fixing it i created a temp migration that wasn't committed to the repo. this migration in this pr refers to that temp migration that's not committed.
this tries to fix the issue by manually changing the hash it points to
> fix: fix hash in migration
