- discord_bots/commands.py
- discord_bots/models.py
> fix: start mu at 12.5

- discord_bots/commands.py
finishgame would finish tie if u misspelled win/loss (f.e: !finishgame won)
> admin for adding map, small finishgame fix

- discord_bots/cogs/rotation.py
Add `!setrotationname <old_rotation_name> <new_rotation_name>` function.
Includes help description
> Feat: SetRotationName

- discord_bots/commands.py
- discord_bots/utils.py
The merge created some issues with these functions. Config variables are no longer in the global scope, so they must be referenced with a config object. The _movegameplayers logic was also in the wrong spot, so I moved that around and did some refactoring to simplify the flow a bit here.
> fix merge issues with create_team_voice_channels and send_in_guild_message, some refactoring

- discord_bots/commands.py
- discord_bots/utils.py
The diff looks weird, but I moved the loop that sends each player a dm to _after_ any interaction.response.sends so there shouldn't be any risk of interaction.response timing out
> fix set_game_code interaction response timing out

- README.md
ReadMe updates for Linux development
> Linux ReadMe Updates

- discord_bots/commands.py
Fixed foreign key constraint error on CancelGame.
Error still exists on FinishGame
((Also moved _movegameplayers() invoke back to the end of CreateGame, so message order is preserved)
> Foreign Key Constraints on CancelGame

- discord_bots/commands.py
- discord_bots/main.py
- discord_bots/utils.py
- discord_bots/views/in_progress_game.py
- finishgame and cancelgame are now slash commands
- When a match gets created, a new text channel which contains an Embed with buttons for finishing the game as a win, loss, or tie
> Add logic for match-channel creation with finish game buttons, migrate finishgame and cancelgame to slash commands

- discord_bots/commands.py
- discord_bots/main.py
- scripts/backtest_win_accuracy.py
Added a script for back testing win prediction accuracy
Also now includes 2 minor changes to bot functionality:
1. The bot will no longer send the "Please use ! commands in #channel" message (this was a mistake: adds spam/can be abused
2. Added quote blocks (">>> ") to the In Progress Game message:
In the case of no players on a team, it will display the ">>> ", but I felt that this was a non-issue.
> Add script for backtesting predicted win accuracy

- discord_bots/commands.py
- discord_bots/tasks.py
Fix hanging invocation of `resolve_predictions()` on `/finishgame`
> Finish game fix

- discord_bots/commands.py
* fix player_category_trueskills to grab trueskills from only in-game players
* switch average_trueskill to be mu.  figure this makes more sense than rank since mu is used for team calculation and that's the value everyone is familiar with
> fix: set average_trueskill to average mu and correct category trueskill calculation

- discord_bots/cogs/in_progress_game.py
- discord_bots/commands.py
- discord_bots/utils.py
fixes typo and removes timestamps on embeds
> slight formatting changes

- discord_bots/cogs/economy.py
- Check for negative value predictions.
- Post prediction results in game history channel
> Fix: Disallow negative predictions

- discord_bots/commands.py
- discord_bots/utils.py
- Adds Economy top 10 to Leaderboard
- Changes `!resetleaderboardchannel` to `/resetleaderboardchannel`
- Cleaned up `print_leaderboard()` to remove old code supporting no categories.
> Feat: Economy Leaderboard

- README.md
- docs/SCRIPTS.md
- scripts/soft_reset.py
Initial implementation of a soft reset script, adapted from [Sauon's implementation](https://github.com/Sauon/discord-bots/blob/master/scriptsv2/soft_reset.py).
> Add Soft Reset Script

- discord_bots/cogs/common.py
- discord_bots/cogs/in_progress_game.py
- discord_bots/utils.py
Very minor change, just moving game code command back to `/setgamecode` due to UX feedback.
Also updated IPG embed to properly display the new `/game finish` command instead of `/finishgame`
> /game setcode -> /setgamecode

- discord_bots/main.py
Seems like the event function defs were changed since this was originally added
> fix: on_join -> on_member_join, on_leave: on_member_remove

- discord_bots/cogs/common.py
- discord_bots/cogs/in_progress_game.py
- discord_bots/cogs/map.py
- discord_bots/cogs/raffle.py
- discord_bots/cogs/rotation.py
- discord_bots/cogs/vote.py
- discord_bots/commands.py
- discord_bots/tasks.py
- discord_bots/utils.py
1. Re-implements `/vote skip` and `/vote map`. They were commented out and work fine after un-commenting them. We'll see if we run into any bugs.
2. Consolidated a large chunk of the autocomplete functions into `utils.py`. Many were being duplicated in separate functions, so instead I consolidated them and used the `@discord.app_commands.autocomplete(...)` decorator. There's some more to go through still
> fix: re-add vote skip and vote map, consolidate autocorrect somewhat

- discord_bots/commands.py
- discord_bots/utils.py
> style: condensed IPG embed in status, remove "map rotated to" message when a game pops

- discord_bots/utils.py
> style: switch back to old leaderboard style, but in regular message

- discord_bots/commands.py
- discord_bots/utils.py
Associate BE = 🔴and DS = 🔵 for the voice channel names and team assignments.
This replaces the existing Left/Right distinction to help make team assignments a little more clear.
> Use red/blue circle emojis to differentiate btw BE/DS, instead of left/right arrow emojis

- discord_bots/cogs/admin.py
Also: Delete players votes. Send success message after the action was successful
> feat: Delete banned player from queues

- alembic/versions/20250607181932_54080d3503e2_make_role_id_bigint.py
> fix: fix it again

- discord_bots/cogs/common.py
- discord_bots/utils.py
This fixes the stats command so that it works even with all the position / map trueskills.
The main solution is to chunk the response
> fix: fix stats to work w/ positions/maps
